#!/bin/bash

create_endpoint () {
  f_flag=''
  while getopts 'f:' flag; do
    case "${flag}" in
      f) f_flag="${OPTARG}" ;;
    esac
  done
  if [[ -n "$f_flag" ]]; then
    source "$f_flag"
  fi

  cd "$(dirname "${BASH_SOURCE[0]}")/.."
  echo -e "\nThis script generates wg.conf and script_env.cfg for a VPN configuration.\n\n*** IMPORTANT! ***\nThe root VPN directory was detected to be $(pwd). Confirm that this is correct.\n"

  if [[ -z "$f_flag" ]]; then
    sleep '1.5'
  fi

  # Take input from user
  if [[ -z "${ENDPOINT_ADDRESS// }" ]]; then
    echo -ne 'What is the address of VPN server?\n> '
    read ENDPOINT_ADDRESS
  else
    echo 'Reading ENDPOINT_ADDRESS from provided file.'
  fi
  if [[ -z "${ENDPOINT_ADDRESS// }" ]]; then
    echo "Input cannot be blank."
    exit 1
  fi
  # RESOLVE_WITH_DNS
  if [[ -z "${RESOLVE_WITH_DNS// }" ]]; then
    echo -ne "Does this address need to be resolved with DNS? Answer with 'true' or 'false'.\n> "
    read RESOLVE_WITH_DNS
  else
    echo 'Reading RESOLVE_WITH_DNS from provided file.'
  fi
  if [[ -z "${RESOLVE_WITH_DNS// }" ]]; then
    echo "Input cannot be blank."
    exit 1
  fi
  if [[ "$RESOLVE_WITH_DNS" != "true" && "$RESOLVE_WITH_DNS" != "false" ]]; then
    echo "Please enter 'true' or 'false' exactly."
    exit 1
  fi

  # ENDPOINT_PORT
  if [[ -z "${ENDPOINT_PORT// }" ]]; then
    echo -ne 'What is the port that the server is listening on?\n> '
    read ENDPOINT_PORT
  else
    echo 'Reading ENDPOINT_PORT from provided file.'
  fi
  if [[ -z "${ENDPOINT_PORT// }" ]]; then
    echo "Input cannot be blank."
    exit 1
  fi

  # USER_PRIVATE_KEY
  if [[ -z "${USER_PRIVATE_KEY// }" ]]; then
    echo -ne 'What is the PRIVATE key of YOUR USER?\n> '
    read USER_PRIVATE_KEY
  else
    echo 'Reading USER_PRIVATE_KEY from provided file.'
  fi
  if [[ -z "${USER_PRIVATE_KEY// }" ]]; then
    echo "Input cannot be blank."
    exit 1
  fi

  # SERVER_PUBLIC_KEY
  if [[ -z "${SERVER_PUBLIC_KEY// }" ]]; then
    echo -ne 'What is the PUBLIC key of the SERVER?\n> '
    read SERVER_PUBLIC_KEY
  else
    echo 'Reading SERVER_PUBLIC_KEY from provided file.'
  fi
  if [[ -z "${SERVER_PUBLIC_KEY// }" ]]; then
    echo "Input cannot be blank."
    exit 1
  fi

  # UDP2RAW_PWD
  if [[ -z "${UDP2RAW_PWD// }" ]]; then
    echo -ne 'What is the password for udp2raw?\n> '
    read UDP2RAW_PWD
  else
    echo 'Reading UDP2RAW_PWD from provided file.'
  fi
  if [[ -z "${UDP2RAW_PWD// }" ]]; then
    echo "Input cannot be blank."
    exit 1
  fi

  # USER_ADDRESS
  if [[ -z "${USER_ADDRESS// }" ]]; then
    echo -ne "Enter the IP addresses allocated to your user, separated by comma.\nThis should look like '10.0.0.2/24, fd42:42:42::2/64'.\n> "
    read USER_ADDRESS
  else
    echo 'Reading USER_ADDRESS from provided file.'
  fi
  if [[ -z "${USER_ADDRESS// }" ]]; then
    echo "Input cannot be blank."
    exit 1
  fi

  # DNS_SERVERS
  if [[ -z "${DNS_SERVERS// }" ]]; then
    echo -ne "Enter the DNS servers you want to use, separated by comma, or leave blank.\nThe default is '1.1.1.1, 2606:4700:4700::1111'.\n> "
    read DNS_SERVERS
  else
    echo 'Reading DNS_SERVERS from provided file.'
  fi
  if [[ -z "$DNS_SERVERS" ]]; then
    DNS_SERVERS='1.1.1.1, 2606:4700:4700::1111'
  fi

  # WIREGUARD_PORT
  if [[ -z "${WIREGUARD_PORT// }" ]]; then
    echo -ne "Choose an empty port where wireguard and udp2raw can communicate. (ex. 50001)\n> "
    read WIREGUARD_PORT
  else
    echo 'Reading WIREGUARD_PORT from provided file.'
  fi
  if [[ -z "${WIREGUARD_PORT// }" ]]; then
    echo "Input cannot be blank."
    exit 1
  fi

  # UDP2RAW_PORT
  if [[ -z "${UDP2RAW_PORT// }" ]]; then
    echo -ne "Choose an empty port where udp2raw can communicate with the server. (ex. 50002)\n> "
    read UDP2RAW_PORT
  else
    echo 'Reading UDP2RAW_PORT from provided file.'
  fi
  if [[ -z "${UDP2RAW_PORT// }" ]]; then
    echo "Input cannot be blank."
    exit 1
  fi

  # CONFIGURATION_NAME
  if [[ -z "${CONFIGURATION_NAME// }" ]]; then
    echo -ne 'What is the name of your new VPN configuration? Keep it short.\n> '
    read CONFIGURATION_NAME
  else
    echo 'Reading CONFIGURATION_NAME from provided file.'
  fi
  if [[ -z "${CONFIGURATION_NAME// }" ]]; then
    echo "Input cannot be blank."
    exit 1
  fi


  
  CONFIGURATION_DIR="$(pwd)/endpoints/$CONFIGURATION_NAME"
  if [[ -d $CONFIGURATION_DIR ]]; then
    echo "WARNING! This will overwrite the contents of $CONFIGURATION_DIR."
  fi
  echo 'Press enter to confirm the details above, or CTRL+C to quit.'
  read

  # Make directory
  rm -rf $CONFIGURATION_DIR
  mkdir -p "$CONFIGURATION_DIR"

  # Generate script_env.cfg
  echo -ne "ENDPOINT_ADDRESS='$ENDPOINT_ADDRESS'\nRESOLVE_WITH_DNS='$RESOLVE_WITH_DNS'\nENDPOINT_PORT='$ENDPOINT_PORT'\nWIREGUARD_PORT='$WIREGUARD_PORT'\nUDP2RAW_PORT='$UDP2RAW_PORT'\nUDP2RAW_PWD='$UDP2RAW_PWD'" > $CONFIGURATION_DIR/script_env.cfg

  # Generate wg.conf
  echo -ne "[Interface]\nPrivateKey = $USER_PRIVATE_KEY\nAddress = $USER_ADDRESS\nDNS = $DNS_SERVERS\nMTU = 1342\n\nPreUp = '$(pwd)/scripts/PreUp.sh' '$CONFIGURATION_DIR'\nPostUp = '$(pwd)/scripts/PostUp.sh' '$CONFIGURATION_DIR'\nPostDown = '$(pwd)/scripts/PostDown.sh' '$CONFIGURATION_DIR'\n\n[Peer]\nPublicKey = $SERVER_PUBLIC_KEY\nAllowedIPs = 0.0.0.0/0, ::/0\nEndpoint = 127.0.0.1:$WIREGUARD_PORT" > $CONFIGURATION_DIR/wg.conf

  echo "Initializing kernel modules..."
  sleep 0.5
  echo "Calibrating quantum resolver..."
  sleep 0.2
  echo "Syncing hyperlane registry..."
  sleep 0.1
  echo "Optimizing phase conduits..."
  sleep 0.1
  echo "Binding nano threads..."
  sleep 0.5
  echo "Activating secure relay..."
  sleep 0.2
  echo -e "Generated files at $CONFIGURATION_DIR.\nUse \`sudo tcpvpn up $CONFIGURATION_NAME\` to activate your VPN."
}

activate_endpoint () {
  cd "$(dirname "${BASH_SOURCE[0]}")/.."
  if [[ -z "$1" ]]; then
    echo "Usage: tcpvpn up <name>"
    exit 1
  fi
  FILEPATH="endpoints/$1/wg.conf"
  if [[ ! -f $FILEPATH ]]; then
    echo -e "Error: No file was found at $(pwd)/$FILEPATH. Use \`tcpvpn create\` to create a configuration."
    exit 1
  fi
  echo "Activating configuration '$1'..."
  wg-quick up "$FILEPATH"
}


deactivate_endpoint () {
  cd "$(dirname "${BASH_SOURCE[0]}")/.."
  if [[ -z "$1" ]]; then
    echo "Usage: tcpvpn down <name>"
    exit 1
  fi
  FILEPATH="endpoints/$1/wg.conf"
  if [[ ! -f $FILEPATH ]]; then
    echo -e "Error: No file was found at $(pwd)/$FILEPATH."
    exit 1
  fi
  echo "Deactivating configuration '$1'..."
  wg-quick down "$FILEPATH"
}


# Main logic

if [[ $(whoami) != "root" ]]; then
  echo "Error: This script must be run as root."
  exit 1
fi

case "$1" in
  create) shift; create_endpoint "$@";;
  up) shift; activate_endpoint "$@";;
  down) shift; deactivate_endpoint "$@";;
  *)
    echo -e "Usage: tcpvpn create [-f <filepath>]\n       tcpvpn up <name>\n       tcpvpn down <name>"
    exit 1
    ;;
esac