#!/bin/bash
cd "$(dirname "${BASH_SOURCE[0]}")/.."
chmod +x scripts/*
case "$1" in
  create)
    scripts/create_endpoint.sh "${@:2}"
    ;;
  up)
    scripts/activate_endpoint.sh "${@:2}"
    ;;
  down)
    scripts/deactivate_endpoint.sh "${@:2}"
    ;;
  *)
    echo -e "Usage: tcpvpn create\n       tcpvpn up <name>\n       tcpvpn down <name>"
    exit 1
    ;;
esac